### ISSUE TITLE
Include Software Identifier in all report records

### ISSUE THREAD

**Issue by cmschmidt** [sacmwg/software-identification#2]
Currently when a software record is reported it can either be reported using the complete record (as expressed in some data model) or it can be reported using a Software Identifier. Since Software Identifiers are derived directly from complete records, I had originally felt that including them along with complete records would be redundant. However, it was pointed out that this decision requires that any recipient understand how to extract the Software Identifier from each supported data model before it can correlate between a full record and a Software Identifier. Not all recipients will necessarily be able to do that. This reduces the utility of Software Identifiers as a primary means of tracking software. It was suggested that the Software Identifier should be present each time a piece of software is reported, whether or not the full record is also sent.

**Comment by djhaynes** [comment]
The WG achieved consensus on this issue on the mailing list (https://www.ietf.org/mail-archive/web/sacm/current/msg04477.html).

The issue was addressed in revision -03 (https://datatracker.ietf.org/doc/draft-coffin-sacm-nea-swid-patnc/).
